"""GitHub REST integration: diff fetch/parse, comment CRUD, check runs.

The bot maintains one living PR comment (found via a signature search) rather
than posting a new comment per push. The footer line
"Generated by MLReviewBot — scikit-learn ML pipeline reviewer" is the
signature that find_bot_comment() greps for.
"""

import logging
import os

import httpx

API_BASE = "https://api.github.com"
SIGNATURE = "Generated by MLReviewBot — scikit-learn ML pipeline reviewer"
CHECK_RUN_SUMMARY_LIMIT = 65536  # GitHub rejects check-run summaries over 64 KiB

logger = logging.getLogger(__name__)


def _headers(accept: str = "application/vnd.github+json") -> dict:
    return {
        "Authorization": f"Bearer {os.environ['GITHUB_TOKEN']}",
        "Accept": accept,
        "X-GitHub-Api-Version": "2022-11-28",
    }


def get_pr_diff(repo: str, pr: int) -> str:
    """Fetch the unified diff via Accept: application/vnd.github.v3.diff."""
    url = f"{API_BASE}/repos/{repo}/pulls/{pr}"
    response = httpx.get(url, headers=_headers("application/vnd.github.v3.diff"), timeout=30)
    response.raise_for_status()
    return response.text


def parse_diff_files(diff: str) -> dict:
    """Reconstruct each changed .py file's new content from the unified diff.

    Walks the diff line by line: "diff --git" starts a new file boundary,
    "+++ b/<path>" sets the current file (only if it ends in .py), "+" lines
    (not "+++") and " " (context) lines are appended with their marker
    stripped. "@@" hunk headers, "-" removed lines, and "\\ No newline" are
    skipped. Returns {path: reconstructed_content}.
    """
    files = {}
    current_file = None
    current_lines = []

    def flush():
        if current_file is not None:
            files[current_file] = "\n".join(current_lines)

    for line in diff.splitlines():
        if line.startswith("diff --git"):
            flush()
            current_file = None
            current_lines = []
        elif line.startswith("+++ b/"):
            path = line[6:]
            current_file = path if path.endswith(".py") else None
            current_lines = []
        elif current_file:
            if line.startswith("+") and not line.startswith("+++"):
                current_lines.append(line[1:])
            elif line.startswith(" "):
                current_lines.append(line[1:])
            # '@@' hunk headers, '-' removed lines, '\ No newline' are skipped

    flush()
    return files


def find_bot_comment(repo: str, pr: int):
    """Paginated scan of PR comments for the bot's signature comment.

    Returns the comment id if found, else None.
    """
    url = f"{API_BASE}/repos/{repo}/issues/{pr}/comments"
    page = 1
    per_page = 100

    while True:
        response = httpx.get(
            url,
            headers=_headers(),
            params={"page": page, "per_page": per_page},
            timeout=30,
        )
        response.raise_for_status()
        comments = response.json()

        for comment in comments:
            if SIGNATURE in comment.get("body", ""):
                return comment["id"]

        if len(comments) < per_page:
            return None
        page += 1


def post_review_comment(repo: str, pr: int, body: str) -> int:
    """Create a new issue comment on the PR; returns its id."""
    url = f"{API_BASE}/repos/{repo}/issues/{pr}/comments"
    response = httpx.post(url, headers=_headers(), json={"body": body}, timeout=30)
    response.raise_for_status()
    return response.json()["id"]


def update_review_comment(repo: str, comment_id: int, body: str) -> None:
    """Edit an existing comment by id."""
    url = f"{API_BASE}/repos/{repo}/issues/comments/{comment_id}"
    response = httpx.patch(url, headers=_headers(), json={"body": body}, timeout=30)
    response.raise_for_status()


def create_check_run(repo: str, sha: str, score: int, passed: bool, summary: str) -> None:
    """Create a GitHub Check Run (green/red merge gate).

    Tolerates real-world failure modes:
    - 403 checks:write missing -> log a warning, don't crash (comment still posted)
    - 64 KiB summary limit -> truncate summary to fit before sending
    """
    if len(summary) > CHECK_RUN_SUMMARY_LIMIT:
        summary = summary[: CHECK_RUN_SUMMARY_LIMIT - 3] + "..."

    url = f"{API_BASE}/repos/{repo}/check-runs"
    payload = {
        "name": "MLReviewBot",
        "head_sha": sha,
        "status": "completed",
        "conclusion": "success" if passed else "failure",
        "output": {
            "title": f"ML Quality Score: {score}/100",
            "summary": summary,
        },
    }

    response = httpx.post(url, headers=_headers(), json=payload, timeout=30)
    if response.status_code == 403:
        logger.warning(
            "Could not create check run for %s@%s — token likely lacks checks:write scope. "
            "Review comment was still posted.",
            repo,
            sha,
        )
        return
    response.raise_for_status()
