name: MLReviewBot
on:
  pull_request:
    paths: ['**.py']
jobs:
  ml-review:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: vai5hnav/mlreviewbot@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          gemini-key: ${{ secrets.GEMINI_API_KEY }}
